### ISSUE TITLE
3D support

### ISSUE THREAD

**Issue by adler-j** [ahendriksen/msd_pytorch#1]
What is the status of 3D support? Will it be implemented?

**Comment by ahendriksen** [comment]
Yes.

**Comment by adler-j** [comment]
Phenomenal!

**Comment by ahendriksen** [comment]
There is still some work to do on the performance front, but 3D convolutions have arrived. I might be able to push a new release before this issue turns 2 years old ;) Huge thanks to @RyanPlt for doing the hard work of porting the CUDA code!
