### ISSUE TITLE
Running with cuda 11.0 

### ISSUE THREAD

**Issue by svvenkatakrishnan** [ahendriksen/msd_pytorch#6]
Hi,  

Is there a way to adapt the code to run with cuda 11 for newer Nvidia systems ? 

Regards

Venkat

**Comment by ahendriksen** [comment]
Hi, 

With Conda, you can install an old cudatoolkit and it will work when the CUDA driver is more recent. So on a CUDA 11 system, installing msd_pytorch on conda with cudatoolkit=10.2 should work fine. 

I am currently pushing some 3D features through. Afterwards, I will devote some attention to becoming compatible with more recent versions of pytorch and cudatoolkit... I hope to have this finished in the next couple of weeks. 

Best, 

Allard

**Comment by svvenkatakrishnan** [comment]
Thank you for the quick response. I tried doing that but still not able to get the code to compile from source.  Specifically I tried 

1) conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.2 -c pytorch

2) pip install .[dev]

File "/anaconda3/envs/msdnet_pytorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
        raise RuntimeError(message)
    RuntimeError: Error compiling objects for extension

Do we have to make changes to the setup.py file ? 

My system has A-100 GPUs. 

P.S. On a older machine with P40s the instructions to compile from source work well.

**Comment by ahendriksen** [comment]
Is there a specific reason you want to install from source rather than use the prebuilt conda packages? i.e:

`conda install msd_pytorch=0.9.1 cudatoolkit=10.2 -c aahendriksen -c pytorch -c defaults -c conda-forge`

If all goes well, you should get the latest version of msd_pytorch, and pytorch version 1.5. 

When compiling from source, the system's nvcc compiler is used by default. This will lead to compatibility issues, as indeed the nvcc compiler is from CUDA version 11, and the runtime toolkit is using 10.2. 

I will work on brining msd_pytorch to newer versions of cuda-toolkit and pytorch today, so I hope that helps fix the issue for you.

**Comment by svvenkatakrishnan** [comment]
I was looking to compile from source in order to be able to modify the code. 

I did try the Conda install suggested and got the following error:

 conda install msd_pytorch=0.9.1 cudatoolkit=10.2 -c aahendriksen -c pytorch -c defaults -c conda-forge

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libstdcxx-ng conflicts for:
msd_pytorch=0.9.1 -> cudatoolkit[version='>=10.1.243,<10.2.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.2.0|>=7.5.0|>=9.3.0']
msd_pytorch=0.9.1 -> libstdcxx-ng[version='>=7.3.0']

Package _libgcc_mutex conflicts for:
msd_pytorch=0.9.1 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1',build='conda_forge|main']
cudatoolkit=10.2 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1',build='conda_forge|main']
python=3.7 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1',build='conda_forge|main']

Package libgcc-ng conflicts for:
msd_pytorch=0.9.1 -> libgcc-ng[version='>=7.3.0']
msd_pytorch=0.9.1 -> cudatoolkit[version='>=10.1.243,<10.2.0a0'] -> libgcc-ng[version='>=4.9|>=7.5.0|>=9.3.0|>=7.2.0']

Package cudatoolkit conflicts for:
msd_pytorch=0.9.1 -> pytorch[version='>=1.5.1,<1.6.0a0'] -> cudatoolkit[version='>=10.0,<10.1|>=10.1,<10.2|>=10.2,<10.3|>=9.2,<9.3']
cudatoolkit=10.2
msd_pytorch=0.9.1 -> cudatoolkit[version='>=10.0.130,<10.1.0a0|>=10.1.243,<10.2.0a0|>=9.2,<9.3.0a0']

**Comment by ahendriksen** [comment]
My apologies.. I should have written cudatoolkit=10.1. 

If you want to edit the code, then I just pushed the branch `move-pytorch-versions-16-and-up` . I tested that it works with pytorch versions 1.4, 1.5, 1.6, 1.7, 1.8 and cudatoolkit 10.2. I hope cudatoolkit 11 works as well.

**Comment by svvenkatakrishnan** [comment]
Thank you @ahendriksen!  I was able to use the code in the new branch with cuda 11 and compiling from source.

**Comment by ahendriksen** [comment]
Happy to help! Let me know if you run into any problems!
